using Portfolio.Domain.Entities;

namespace Portfolio.Infrastructure.Persistence;

// Real InvoGames portfolio titles (from invogames.com/our-work) that Shoaib contributed to
// as Senior Game Engineer. Descriptions are sourced from each project's public page summary.
public static class ProjectSeedData
{
    private const string RoleGameplay =
        "As Senior Game Engineer at InvoGames, I worked on gameplay systems, client–server and backend integration, third-party SDKs, and performance optimization to bring this title to production.";
    private const string RoleXR =
        "As Senior Game Engineer at InvoGames, I worked on the Unity/XR implementation, real-time interaction systems, backend integration, and performance optimization for this immersive experience.";
    private const string RoleWeb3 =
        "As Senior Game Engineer at InvoGames, I worked on real-time gameplay, backend/web integration, and the on-chain/Web3 and data-driven systems powering this experience.";

    public static List<Project> InvoGamesProjects() => new()
    {
        new() { Slug = "rage-war", Title = "Rage War", Category = "Strategy RPG", IsFeatured = true,
            TechStack = "Unity, C#, Backend APIs", MyRole = RoleGameplay,
            Summary = "City-building, hero battles, and strategy combined in a fast, action-packed RPG built with Unity.",
            Description = "Rage War brings city-building, hero battles, and real-time strategy together in one fast, fun, action-packed RPG. Built with Unity, it blends base management with combat progression and live-ops driven content." },
        new() { Slug = "atomic-golf", Title = "Atomic Golf", Category = "Sports Game", IsFeatured = true,
            TechStack = "Unity, Node.js, REST APIs", MyRole = RoleGameplay,
            Summary = "Real-time gaming experience with zero downtime, powered by Unity and Node.js.",
            Description = "Atomic Golf redefined its digital experience with real-time gameplay updates, seamless backend integrations, and a no-disruption deployment approach — powered by Unity on the client and Node.js services on the backend." },
        new() { Slug = "fps-survival-game", Title = "Multiplayer Survival FPS", Category = "FPS / Multiplayer", IsFeatured = true,
            TechStack = "Unreal Engine, AWS EC2, Multiplayer", MyRole = RoleGameplay,
            Summary = "A fast-paced multiplayer FPS with real-time matchmaking and session handling, built on Unreal & AWS.",
            Description = "A fast-paced first-person shooter built with Unreal Engine and AWS EC2, featuring real-time matchmaking, lobby control, and robust multiplayer session handling for low-latency competitive play." },
        new() { Slug = "hoof-clash-rider", Title = "Medieval Arena", Category = "Multiplayer Combat", IsFeatured = true,
            TechStack = "Unreal Engine 5, Multiplayer", MyRole = RoleGameplay,
            Summary = "5v5 mounted combat with stamina-based melee, weapon classes, and trap-filled arenas in UE5.",
            Description = "Medieval Arena combines 5v5 mounted combat, stamina-based melee, weapon classes, and trap-filled arenas in a Unreal Engine 5 multiplayer game for PC." },
        new() { Slug = "tire-burners", Title = "Tire Burners", Category = "Racing", IsFeatured = true,
            TechStack = "Unity, Multiplayer", MyRole = RoleGameplay,
            Summary = "Custom track building, multiplayer racing, NOS stunts, and a full reward system in one high-speed PC game.",
            Description = "Tire Burners brings custom track building, multiplayer racing, NOS stunts, and a complete reward system together in one high-speed PC racing game." },
        new() { Slug = "vampire-capitalist", Title = "Vampire Capitalist", Category = "GPS Strategy", IsFeatured = true,
            TechStack = "Unity, MERN, GPS", MyRole = RoleWeb3,
            Summary = "An economic strategy game with a vampire twist and real-world GPS point-of-interest action.",
            Description = "Vampire Capitalist is a strategy game with a vampire twist — real-world point-of-interest action via GPS and MERN-powered backend smarts that make profit-hunting a spooky good time." },
        new() { Slug = "xdog-metadog", Title = "MetaDog", Category = "Web3 Game", IsFeatured = true,
            TechStack = "Unity, Blockchain, Web3", MyRole = RoleWeb3,
            Summary = "High-speed dog racing, crypto betting, and meme-token madness — live and fully on-chain.",
            Description = "MetaDog brought high-speed racing, crypto betting, and meme-token madness together — live, on-chain, and fully Web3." },
        new() { Slug = "drb-saudi-nft-club", Title = "DRB — Saudi NFT Club", Category = "Web3 / 3D Experience", IsFeatured = false,
            TechStack = "WebGL, 3D, NFT, Multiplayer", MyRole = RoleWeb3,
            Summary = "A web-based 3D experience blending Saudi heritage, multiplayer, NFT minting, and e-commerce.",
            Description = "DRB is a web-based 3D experience combining Saudi heritage, multiplayer interaction, NFT minting, and e-commerce within immersive cultural environments." },
        new() { Slug = "vr-music-app", Title = "VR Music Learning App", Category = "AR/VR", IsFeatured = true,
            TechStack = "Unity, Apple Vision Pro, XR, LMS", MyRole = RoleXR,
            Summary = "Learn instruments in VR with hand gestures, real-time feedback, and guided lessons on Apple Vision Pro.",
            Description = "An immersive VR instrument-learning app built for Apple Vision Pro — hand-gesture interaction, real-time feedback, and guided lessons for all skill levels, with LMS integration." },
        new() { Slug = "unity-xr-hand-gesture", Title = "Hands Gesture XR Pack", Category = "AR/VR Package", IsFeatured = false,
            TechStack = "Unity, VR/AR, XR Toolkit", MyRole = RoleXR,
            Summary = "A Unity XR asset pack powering VR/AR with natural hand gestures and optimized performance.",
            Description = "The Hands Gesture XR Asset Pack powers Unity VR/AR with natural hand gestures, optimized runtime performance, and developer-friendly integration." },
        new() { Slug = "vixi-suite", Title = "VIXI Suite", Category = "3D Platform / AI", IsFeatured = false,
            TechStack = "3D, AI, WebGL", MyRole = RoleWeb3,
            Summary = "A 3D content platform that lets publishers create immersive content without the tech struggle.",
            Description = "VIXI Suite is a 3D platform that lets publishers create immersive content without the technical struggle — an easy UI plus real-time AI that drives real business results." },
        new() { Slug = "twin-tech", Title = "TwinTech Dashboard", Category = "IoT / 3D Data", IsFeatured = false,
            TechStack = "WebGL, 3D, IoT", MyRole = RoleWeb3,
            Summary = "A live 3D data dashboard bringing IoT telemetry to life with a zero-stress experience.",
            Description = "TwinTech Dashboard brings live IoT data to life through an interactive 3D experience — built differently with InvoGames for a zero-stress, real-time data view." },
        new() { Slug = "we-cut-trees", Title = "We Cut Trees", Category = "Simulation / Training", IsFeatured = false,
            TechStack = "Unity, 3D Physics, Mobile", MyRole = RoleGameplay,
            Summary = "A mobile crane-operator training simulator using 3D simulation, real physics, and offline access.",
            Description = "We Cut Trees turns mobile devices into crane-operator training tools using 3D simulation, real physics, touch controls, and full offline access." },
        new() { Slug = "farming-simulator", Title = "Farming Simulator", Category = "Simulation", IsFeatured = false,
            TechStack = "Unreal Engine, Android", MyRole = RoleGameplay,
            Summary = "A mobile farming simulator for Android built with Unreal Engine, from design through launch.",
            Description = "A mobile Farming Simulator for Android built with Unreal Engine — covering design, development, optimization, and real results from testing through launch." },
        new() { Slug = "web-pilot-card-game", Title = "Web-Pilot Card Game", Category = "Card Game", IsFeatured = false,
            TechStack = "Unity, React, Multiplayer", MyRole = RoleGameplay,
            Summary = "A 3D card game with smooth player connections, robust admin tools, and immersive play.",
            Description = "The Web-Pilot Card Game redefines card gaming with immersive 3D experiences, smooth player connections, and robust admin tools — powered by Unity and React." },
        new() { Slug = "bigstakes5", Title = "Big Stakes 5", Category = "Card / Social Game", IsFeatured = false,
            TechStack = "Unity, Backend APIs", MyRole = RoleGameplay,
            Summary = "Dominoes blended with poker-style risk, smart scoring, and patented gameplay.",
            Description = "Big Stakes 5 blends dominoes with poker-style risk, smart scoring, and patented gameplay — a standout in the social gaming space." },
        new() { Slug = "sqrrrl", Title = "SQRRRL", Category = "Mobile Tournament", IsFeatured = false,
            TechStack = "Unity, Backend APIs", MyRole = RoleGameplay,
            Summary = "A smooth, prize-packed daily-tournament mobile game that's fast and easy to play.",
            Description = "From concept to daily-tournament hit — SQRRRL was built into a smooth, prize-packed mobile game that's fun, fast, and easy to play." },
        new() { Slug = "gino-devolution", Title = "Gino Devolution", Category = "2D Fighting", IsFeatured = false,
            TechStack = "Unity, Web", MyRole = RoleGameplay,
            Summary = "A 2D fighting game where your fighter evolves mid-battle — playable anywhere, no download.",
            Description = "Gino Devolution is a 2D fighting game where your fighter evolves mid-battle — fast, fun, packed with style, and playable in the browser with no download needed." },
        new() { Slug = "miss-mafia", Title = "Miss Mafia", Category = "Action", IsFeatured = false,
            TechStack = "Unity", MyRole = RoleGameplay,
            Summary = "A cyberpunk action experience with dual-perspective combat and emotional storytelling.",
            Description = "Miss Mafia transforms cyberpunk action into an immersive dual-perspective experience, featuring revolutionary combat mechanics and emotional storytelling through Reiri's story." },
        new() { Slug = "allie-the-ellie", Title = "Ellie the Ellie", Category = "Educational Game", IsFeatured = false,
            TechStack = "Unity, Cross-platform", MyRole = RoleGameplay,
            Summary = "An educational game for kids aged 3–6 with playful mini-games and colorful animation.",
            Description = "Ellie the Ellie brings learning to life for kids aged 3 to 6 through playful mini-games, colorful animation, and smooth cross-platform performance." },
        new() { Slug = "apt-piano-game", Title = "ATP Piano Game", Category = "Music / Educational", IsFeatured = false,
            TechStack = "Unity", MyRole = RoleGameplay,
            Summary = "Turns piano lessons into a game — learn, level up, and flex your skills.",
            Description = "ATP Piano Game flips boring piano lessons into a full-blown vibe — learn, level up, and flex your skills like playing your favorite game." },
        new() { Slug = "time-breakers", Title = "Time Breakers", Category = "Game", IsFeatured = false,
            TechStack = "Unity", MyRole = RoleGameplay,
            Summary = "An action title developed at InvoGames with Unity.",
            Description = "Time Breakers is an action game developed at InvoGames, built with Unity and backend-driven gameplay systems." },
        new() { Slug = "spinning-wheel-game", Title = "Spin the Wheel", Category = "Casual", IsFeatured = false,
            TechStack = "Unity, Web", MyRole = RoleGameplay,
            Summary = "A fast, mobile-friendly spin-to-win game with smooth animations and one-click rewards.",
            Description = "A fast, mobile-friendly spin game with real prizes — built with smooth animations, easy controls, and one-click access to rewards." },
        new() { Slug = "treace-medical", Title = "Treace Medical", Category = "Healthcare / Web", IsFeatured = false,
            TechStack = "Web, Integrations", MyRole = RoleWeb3,
            Summary = "A case study boosting efficiency and leads for a medical-device company's tech flow.",
            Description = "Treace Medical wanted to lead the medical-device space and help people walk pain-free — this engagement modernized their technology flow to boost efficiency and lead generation." },
    };
}
